config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :courts
  resources :gyms
  resources :saunas
  resources :saunas
  resources :kids_pools
  resources :adult_pools
  resources :assembly_rooms
  resources :barbecue_grills
  resources :contatos
  devise_for :users
  root 'resort#index'
  resources :registers
  get 'inicio' => 'resort#index'
  get 'option' => 'option#index'
  get 'contato'=> 'contatos#index'
  get 'choice' => 'choice#index'
  get 'reserve' => 'reserve#index'

end

app/models/adult_pool.rb
class AdultPool < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/assembly_room.rb
class AssemblyRoom < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
	validates :date, presence: true
	validates :date, uniqueness: true
end

app/models/barbecue_grill.rb
class BarbecueGrill < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
	validates :date, presence: true
	validates :date, uniqueness: true
end

app/models/contato.rb
class Contato < ActiveRecord::Base
end

app/models/court.rb
class Court < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/gym.rb
class Gym < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/kids_pool.rb
class KidsPool < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/sauna.rb
class Sauna < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/kids_pools_controller.rb
class KidsPoolsController < ApplicationController
  before_action :set_kids_pool, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /kids_pools
  # GET /kids_pools.json
  def index
    @kids_pools = KidsPool.all
  end

  # GET /kids_pools/1
  # GET /kids_pools/1.json
  def show
  end

  # GET /kids_pools/new
  def new
    @kids_pool = KidsPool.new
  end

  # GET /kids_pools/1/edit
  def edit
  end

  # POST /kids_pools
  # POST /kids_pools.json
  def create
    @kids_pool = KidsPool.new(kids_pool_params)

    respond_to do |format|
      if @kids_pool.save
        format.html { redirect_to @kids_pool }
        format.json { render :show, status: :created, location: @kids_pool }
      else
        format.html { render :new }
        format.json { render json: @kids_pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids_pools/1
  # PATCH/PUT /kids_pools/1.json
  def update
    respond_to do |format|
      if @kids_pool.update(kids_pool_params)
        format.html { redirect_to @kids_pool }
        format.json { render :show, status: :ok, location: @kids_pool }
      else
        format.html { render :edit }
        format.json { render json: @kids_pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids_pools/1
  # DELETE /kids_pools/1.json
  def destroy
    @kids_pool.destroy
    respond_to do |format|
      format.html { redirect_to kids_pools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kids_pool
      @kids_pool = KidsPool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kids_pool_params
      params.require(:kids_pool).permit(:date, :idUser)
    end
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/kids_pools_helper.rb
module KidsPoolsHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
end

app/helpers/option_helper.rb
module OptionHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reserve_helper.rb
module ReserveHelper
end

app/helpers/resort_helper.rb
module ResortHelper
end

app/helpers/saunas_helper.rb
module SaunasHelper
end

app/views/kids_pools/_form.html.erb
<%= form_for(@kids_pool) do |f| %>
  <% if @kids_pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kids_pool.errors.count, "error") %> prohibited this kids_pool from being saved:</h2>

      <ul>
      <% @kids_pool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :idUser %><br>
    <%= f.text_field :idUser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kids_pools/edit.html.erb
<h1>Editing Kids Pool</h1>

<%= render 'form' %>

<%= link_to 'Show', @kids_pool %> |
<%= link_to 'Back', kids_pools_path %>

app/views/kids_pools/index.html.erb
<p id="notice"><%= notice %></p>

<% if policy(@kids_pools).index? %>

<h1>Listing Customers</h1>

  <tbody>
    <% @kids_pools.each do |kids_pool| %>
      <tr>
        <h4>Id User:</h4>
        <td><%= kids_pool.idUser %></td><br>
        <td><%= link_to 'Show', kids_pool %></td>
        <td><%= link_to 'Edit', edit_kids_pool_path(kids_pool) %></td>
        <td><%= link_to 'Destroy', kids_pool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <br/><hr />
    <% end %>
  </tbody>
</table>

<br>

<% else %>

<h3><%= link_to 'Register in this area', new_kids_pool_path %></h3>

<% end %>

<center>
  <img class="img-responsive img-centered" src="img/kidpool.jpg" alt="">
</center>

app/views/kids_pools/new.html.erb
<h1>New Kids Pool</h1>

<%= render 'form' %>

<%= link_to 'Back', kids_pools_path %>

app/views/kids_pools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Iduser:</strong>
  <%= @kids_pool.idUser %>
</p>

<%= link_to 'Edit', edit_kids_pool_path(@kids_pool) %> |
<%= link_to 'Back', kids_pools_path %>