config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :courts
  resources :gyms
  resources :saunas
  resources :saunas
  resources :kids_pools
  resources :adult_pools
  resources :assembly_rooms
  resources :barbecue_grills
  resources :contatos
  devise_for :users
  root 'resort#index'
  resources :registers
  get 'inicio' => 'resort#index'
  get 'option' => 'option#index'
  get 'contato'=> 'contatos#index'
  get 'choice' => 'choice#index'
  get 'reserve' => 'reserve#index'

end

app/models/adult_pool.rb
class AdultPool < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/assembly_room.rb
class AssemblyRoom < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
	validates :date, presence: true
	validates :date, uniqueness: true
end

app/models/barbecue_grill.rb
class BarbecueGrill < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
	validates :date, presence: true
	validates :date, uniqueness: true
end

app/models/contato.rb
class Contato < ActiveRecord::Base
end

app/models/court.rb
class Court < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/gym.rb
class Gym < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/kids_pool.rb
class KidsPool < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/sauna.rb
class Sauna < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :set_court, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /courts
  # GET /courts.json
  def index
    @courts = Court.all
  end

  # GET /courts/1
  # GET /courts/1.json
  def show
  end

  # GET /courts/new
  def new
    @court = Court.new
  end

  # GET /courts/1/edit
  def edit
  end

  # POST /courts
  # POST /courts.json
  def create
    @court = Court.new(court_params)

    respond_to do |format|
      if @court.save
        format.html { redirect_to @court }
        format.json { render :show, status: :created, location: @court }
      else
        format.html { render :new }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courts/1
  # PATCH/PUT /courts/1.json
  def update
    respond_to do |format|
      if @court.update(court_params)
        format.html { redirect_to @court }
        format.json { render :show, status: :ok, location: @court }
      else
        format.html { render :edit }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courts/1
  # DELETE /courts/1.json
  def destroy
    @court.destroy
    respond_to do |format|
      format.html { redirect_to courts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_court
      @court = Court.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def court_params
      params.require(:court).permit(:date, :idUser)
    end
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
end

app/helpers/option_helper.rb
module OptionHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reserve_helper.rb
module ReserveHelper
end

app/helpers/resort_helper.rb
module ResortHelper
end

app/helpers/saunas_helper.rb
module SaunasHelper
end

app/views/courts/_form.html.erb
<%= form_for(@court) do |f| %>
  <% if @court.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@court.errors.count, "error") %> prohibited this court from being saved:</h2>

      <ul>
      <% @court.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idUser %><br>
    <%= f.text_field :idUser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courts/edit.html.erb
<h1>Editing Court</h1>

<%= render 'form' %>

<%= link_to 'Show', @court %> |
<%= link_to 'Back', courts_path %>

app/views/courts/index.html.erb
<p id="notice"><%= notice %></p>

<% if policy(@courts).index? %>

<h1>Listing Courts</h1>

  <tbody>
    <% @courts.each do |court| %>
      <tr>
        <h4>Id User:</h4>
        <td><%= court.idUser %></td><br>
        <td><%= link_to 'Show', court %></td>
        <td><%= link_to 'Edit', edit_court_path(court) %></td>
        <td><%= link_to 'Destroy', court, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <br/><hr />
    <% end %>
  </tbody>
</table>

<br>

<% else %>

<h3><%= link_to 'Register in this area', new_court_path %></h3>

<% end %>


<center>
  <img class="img-responsive img-centered" src="img/court.jpg" alt="">
</center>

app/views/courts/new.html.erb
<h1>New Court</h1>

<%= render 'form' %>

<%= link_to 'Back', courts_path %>

app/views/courts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Iduser:</strong>
  <%= @court.idUser %>
</p>

<%= link_to 'Edit', edit_court_path(@court) %> |
<%= link_to 'Back', courts_path %>