config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :courts
  resources :gyms
  resources :saunas
  resources :saunas
  resources :kids_pools
  resources :adult_pools
  resources :assembly_rooms
  resources :barbecue_grills
  resources :contatos
  devise_for :users
  root 'resort#index'
  resources :registers
  get 'inicio' => 'resort#index'
  get 'option' => 'option#index'
  get 'contato'=> 'contatos#index'
  get 'choice' => 'choice#index'
  get 'reserve' => 'reserve#index'

end

app/models/adult_pool.rb
class AdultPool < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/assembly_room.rb
class AssemblyRoom < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
	validates :date, presence: true
	validates :date, uniqueness: true
end

app/models/barbecue_grill.rb
class BarbecueGrill < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
	validates :date, presence: true
	validates :date, uniqueness: true
end

app/models/contato.rb
class Contato < ActiveRecord::Base
end

app/models/court.rb
class Court < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/gym.rb
class Gym < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/kids_pool.rb
class KidsPool < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/sauna.rb
class Sauna < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:tittle, :content, :data)
    end
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
end

app/helpers/option_helper.rb
module OptionHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reserve_helper.rb
module ReserveHelper
end

app/helpers/resort_helper.rb
module ResortHelper
end

app/helpers/saunas_helper.rb
module SaunasHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tittle %><br>
    <%= f.text_field :tittle %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Notices</h1> 

<% if policy(@posts).index? %>

  <tbody>

    <% for post in @posts.reverse %>
      <tr> 
        <h3><%= link_to post.tittle, post %></h3>
        <h5><%= post.data.to_s(:long) %></h5>
        <p><%= post.tittle %></p>
        
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <tr/>   
        <br/><hr />

    <% end %>
<br>

<%= link_to 'New Post', new_post_path %>

<% else %>

    <% for post in @posts.reverse %>
      <tr> 

        <h2><%= post.tittle %></h2>
        <h5><%= post.data.to_s(:long) %></h5>
        <p><%= post.tittle %></p>
        <h4><%= post.content %></h4>
        
    <tr/>   
        <br/><hr />

    <% end %>

<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tittle:</strong>
  <%= @post.tittle %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Data:</strong>
  <%= @post.data %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>