config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :courts
  resources :gyms
  resources :saunas
  resources :saunas
  resources :kids_pools
  resources :adult_pools
  resources :assembly_rooms
  resources :barbecue_grills
  resources :contatos
  devise_for :users
  root 'resort#index'
  resources :registers
  get 'inicio' => 'resort#index'
  get 'option' => 'option#index'
  get 'contato'=> 'contatos#index'
  get 'choice' => 'choice#index'
  get 'reserve' => 'reserve#index'

end

app/models/adult_pool.rb
class AdultPool < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/assembly_room.rb
class AssemblyRoom < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
	validates :date, presence: true
	validates :date, uniqueness: true
end

app/models/barbecue_grill.rb
class BarbecueGrill < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
	validates :date, presence: true
	validates :date, uniqueness: true
end

app/models/contato.rb
class Contato < ActiveRecord::Base
end

app/models/court.rb
class Court < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/gym.rb
class Gym < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/kids_pool.rb
class KidsPool < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/sauna.rb
class Sauna < ActiveRecord::Base
	validates :idUser, presence: true
	validates :idUser, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/saunas_controller.rb
class SaunasController < ApplicationController
  before_action :set_sauna, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /saunas
  # GET /saunas.json
  def index
    @saunas = Sauna.all
  end

  # GET /saunas/1
  # GET /saunas/1.json
  def show
  end

  # GET /saunas/new
  def new
    @sauna = Sauna.new
  end

  # GET /saunas/1/edit
  def edit
  end

  # POST /saunas
  # POST /saunas.json
  def create
    @sauna = Sauna.new(sauna_params)

    respond_to do |format|
      if @sauna.save
        format.html { redirect_to @sauna }
        format.json { render :show, status: :created, location: @sauna }
      else
        format.html { render :new }
        format.json { render json: @sauna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saunas/1
  # PATCH/PUT /saunas/1.json
  def update
    respond_to do |format|
      if @sauna.update(sauna_params)
        format.html { redirect_to @sauna }
        format.json { render :show, status: :ok, location: @sauna }
      else
        format.html { render :edit }
        format.json { render json: @sauna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saunas/1
  # DELETE /saunas/1.json
  def destroy
    @sauna.destroy
    respond_to do |format|
      format.html { redirect_to saunas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sauna
      @sauna = Sauna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sauna_params
      params.require(:sauna).permit(:date, :idUser)
    end
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
end

app/helpers/option_helper.rb
module OptionHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reserve_helper.rb
module ReserveHelper
end

app/helpers/resort_helper.rb
module ResortHelper
end

app/helpers/saunas_helper.rb
module SaunasHelper
end

app/views/saunas/_form.html.erb
<%= form_for(@sauna) do |f| %>
  <% if @sauna.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sauna.errors.count, "error") %> prohibited this sauna from being saved:</h2>

      <ul>
      <% @sauna.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :idUser %><br>
    <%= f.text_field :idUser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/saunas/edit.html.erb
<h1>Editing Sauna</h1>

<%= render 'form' %>

<%= link_to 'Show', @sauna %> |
<%= link_to 'Back', saunas_path %>

app/views/saunas/index.html.erb
<p id="notice"><%= notice %></p>

<% if policy(@saunas).index? %>

<% if policy(@saunas).index2? %>

<h1>Listing Customers</h1>

  <tbody>
    <% @saunas.each do |sauna| %>
      <tr>
        <h4>Id User:</h4>
        <td><%= sauna.idUser %></td><br>
        <td><%= link_to 'Show', sauna %></td>
        <td><%= link_to 'Edit', edit_sauna_path(sauna) %></td>
        <td><%= link_to 'Destroy', sauna, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <br/><hr />
    <% end %>
  </tbody>
</table>

<br>

<% else %>

<h3><%= link_to 'Register in this area', new_sauna_path %></h3>

<% end %>

<% else %>

<h1>This service is available only to those over 15 years old</h1>
        
<% end %>

<center>
  <img class="img-responsive img-centered" src="img/sauna.jpg" alt="">
</center>

app/views/saunas/new.html.erb
<h1>New Sauna</h1>

<%= render 'form' %>

<%= link_to 'Back', saunas_path %>

app/views/saunas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Iduser:</strong>
  <%= @sauna.idUser %>
</p>

<%= link_to 'Edit', edit_sauna_path(@sauna) %> |
<%= link_to 'Back', saunas_path %>